-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        shadow = {
            enabled = false,
        },
    },
    general = {
        border_size = 0,
        gaps_in = 1,
        gaps_out = 1,
    },
})
